name: note build
# 触发workflow的条件
on:
  push:
    branches: ["doc-v2"]

env:
  SERVER_PRIVATE_KEY: ${{ secrets.SERVER_PRIVATE_KEY }} # 服务器私钥
  SERVER_HOST: ${{ secrets.SERVER_HOST }} # 服务器IP地址
  SERVER_POSR: ${{ secrets.SERVER_PORT }} # 服务器端口
  USER_NAME: ${{ secrets.SERVER_USER_NAME }} # 服务器用户名
  cache-name: note
  TZ: Asia/Shanghai # 设置当前环境时区

# jobs表示执行的一项或多项任务
jobs:
  build: # 任务的job_id，具体名称自定义，这里build代表打包
    runs-on: ubuntu-latest # runs-on字段指定运行所需要的虚拟机环境。注意：这个是必填字段
    steps:
      - uses: pnpm/action-setup@v2
        with:
          version: 6.32.9
      - uses: actions/setup-node@v3
        with:
          node-version: "14"
          cache: "pnpm"
      - run: pnpm install --frozen-lockfile

      # 打包
      - name: Build
        run: pnpm docs:build

      # 上传打包资源
      - name: Deploy
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_PRIVATE_KEY }}
          ARGS: "-rltgoDzvO --delete"
          SOURCE: "docs/.vuepress/dist/"
          REMOTE_HOST: ${{ secrets.SERVER_HOST }}
          REMOTE_PORT: ${{ secrets.SERVER_PORT }} -o HostKeyAlgorithms=+ssh-rsa -o PubkeyAcceptedKeyTypes=+ssh-rsa
          REMOTE_USER: ${{ secrets.SERVER_USER_NAME }}
          TARGET: /data/apps/data/docs-im-beta2/ # 服务器目标路径
