name: note build
# 触发workflow的条件
on:
  push:
    branches: ["doc-v2"]

env:
  SERVER_PRIVATE_KEY: ${{ secrets.SERVER_PRIVATE_KEY }} # 服务器私钥
  SERVER_HOST: ${{ secrets.SERVER_HOST }} # 服务器IP地址
  SERVER_POSR: ${{ secrets.SERVER_PORT }} # 服务器端口
  USER_NAME: ${{ secrets.SERVER_USER_NAME }} # 服务器用户名
  cache-name: note
  TZ: Asia/Shanghai # 设置当前环境时区

# jobs表示执行的一项或多项任务
jobs:
  build: # 任务的job_id，具体名称自定义，这里build代表打包
    runs-on: ubuntu-latest # runs-on字段指定运行所需要的虚拟机环境。注意：这个是必填字段
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      #             #缓存依赖
      #             - name: Cache nodemodules
      #               uses: actions/cache@v1
      #               env:
      #                   cache-name: cache-node-modules
      #               with:
      #                   # 需要缓存的文件的路径
      #                   path: ./node_modules
      #                   # 对缓存的文件指定的唯一标识
      #                   key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('./yarn.lock') }}
      #                   # 用于没有再找目标key的缓存的backup选项
      #                   restore-keys: |
      #                       ${{ runner.os }}-build-${{ env.cache-name }}-
      #                       ${{ runner.os }}-build-
      #                       ${{ runner.os }}-
      # 装依赖
      - name: Install
        run: pnpm install

      # 打包
      - name: Build
        run: pnpm docs:build

      # 上传打包资源
      - name: Deploy
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_PRIVATE_KEY }}
          ARGS: "-rltgoDzvO --delete"
          SOURCE: "docs/.vuepress/dist/"
          REMOTE_HOST: ${{ secrets.SERVER_HOST }}
          REMOTE_PORT: ${{ secrets.SERVER_PORT }} -o HostKeyAlgorithms=+ssh-rsa -o PubkeyAcceptedKeyTypes=+ssh-rsa
          REMOTE_USER: ${{ secrets.SERVER_USER_NAME }}
          TARGET: /data/apps/data/docs-im-beta2/ # 服务器目标路径
